### ISSUE TITLE
movegroup: moveLocError and dbblocationerror location error the same, move error not used?

### ISSUE THREAD

**Issue by mauritsvzb** [SimonDedman/movegroup#10]

**Comment by SimonDedman** [comment]
both are used but seemingly identically.

**Comment by SimonDedman** [comment]
L181 function defaults: `dbblocationerror = moveLocError`
`moveLocError` L420-438 same as `dbblocationerror` L464-482 but `dbblocationerror` then has L485 which converts zeroes to 0.`00001`. `dbblocationerror.i` is then used in `move::brownian.bridge.dyn` as `location.error` param; `moveLocError` doesn't appear to be used anywhere.

`dbblocationerror` replaced with `moveLocError` L464-485 & L493
