### ISSUE TITLE
Plotting - cannot plot contour lines without surfaceUD

### ISSUE THREAD

**Issue by mauritsvzb** [SimonDedman/movegroup#8]
No contour lines are plotted if surfaceUD is set to FALSE

**Comment by SimonDedman** [comment]
Still broken and also lat/lon values in axes are way wrong.

**Comment by SimonDedman** [comment]
Yet map output & tiles are correct. surface sets the axes, overriding ggmap default?

add sf::st_transform(3857) to contours to see if they can train the scales also
